stages:
  - build
  - deploy

build backend:
  stage: build
  tags:
    - backend
  script:
    - ./mvnw package
    - docker build -t web-project-backend .

deploy backend:
  stage: deploy
  tags:
    - backend
  script:
    - cd /opt/web-project/backend
    - docker-compose down
    - docker-compose up -d