stages:
  - build
  - deploy

build backend:
  stage: build
  only:
    refs:
      - master
  tags:
    - backend-runner
  script:
    - docker run --name postgres -e POSTGRES_PASSWORD=docker -d postgres
    - ./mvnw package
    - docker build -t web-project-backend .

deploy backend:
  stage: deploy
  only:
    refs:
      - master
  tags:
    - backend-runner
  script:
    - cd /opt/web-project/backend
    - docker-compose down
    - docker-compose up -d