version: "3.7"
services:
    web-project:
        image: web-project-backend:latest
        container_name: web-project-backend
        restart: always
        ports:
            - "8080:8080"
        volumes:
            - /opt/web-project/backend/application.properties:/app/application.properties
    postgres:
        image: postgres:14.1
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=docker
        ports:
            - '5432:5432'
        volumes:
            - ./postgres-data:/var/lib/postgresql/data